Repository diwako/armor_plates_system, pull requests merged in 2021-07, with the labels that each got.

#32 Polish strings added
  addons/main/stringtable.xml
Labels: translation

#36 add confirmation dialog for "Give up" action
  addons/main/functions/fnc_addPlayerHoldActions.sqf
  addons/main/initSettings.sqf
  addons/main/stringtable.xml
Labels: enhancement

#35 Fix self revive when healing under fire
  addons/main/XEH_PREP.hpp
  addons/main/XEH_postInit.sqf
  addons/main/functions/fnc_addActionsToUnit.sqf
  addons/main/functions/fnc_addPlayerHoldActions.sqf
  addons/main/functions/fnc_aiMoveAndHealUnit.sqf
  addons/main/functions/fnc_handleHealEh.sqf
  addons/main/functions/fnc_moduleHeal.sqf
  addons/main/functions/fnc_receiveDamage.sqf
  addons/main/functions/fnc_revive.sqf
  addons/main/functions/fnc_setUnconscious.sqf
Labels: bug

#34 fix ace_medical_allowDamage flag usage
  addons/main/functions/fnc_handleDamageEhACE.sqf
Labels: bug

#37 Update stringtable.xml
  addons/main/stringtable.xml
Labels: translation
