Repository diwako/armor_plates_system, pull requests merged in 2021-06, with the labels that each got.

#2 Add protect only torso setting
  addons/main/functions/fnc_receiveDamage.sqf
  addons/main/initSettings.sqf
  addons/main/stringtable.xml
Labels: enhancement

#9 fix initial left click issue with ace dragging
  addons/main/XEH_postInit.sqf
Labels: bug

#8 fix for ace dragging causing issues
  addons/main/XEH_postInit.sqf
  addons/main/functions/fnc_handleHealEh.sqf
  addons/main/functions/fnc_setUnconscious.sqf
Labels: bug

#3 Add 3den slider to set max HP of individual units
  addons/main/CfgEden.hpp
  addons/main/XEH_postInit.sqf
  addons/main/config.cpp
  addons/main/functions/fnc_handleHealEh.sqf
  addons/main/functions/fnc_receiveDamage.sqf
  addons/main/functions/fnc_showDamageFeedbackMarker.sqf
  addons/main/functions/fnc_startHpRegen.sqf
  addons/main/functions/fnc_updateHPUi.sqf
  addons/main/stringtable.xml
Labels: enhancement

#11 Fix reviving while downed
  addons/main/functions/fnc_addActionsToUnit.sqf
Labels: bug

#6 Polish language for stringtable.xml
  addons/main/stringtable.xml
Labels: translation

#10 Add allow self revive option and action
  addons/main/functions/fnc_addPlayerHoldActions.sqf
  addons/main/initSettings.sqf
  addons/main/stringtable.xml
Labels: enhancement

#4 Add further ACE medical rewrite support
  README.md
  addons/main/CfgWeapons.hpp
  addons/main/XEH_PREP.hpp
  addons/main/XEH_postInit.sqf
  addons/main/XEH_preInit.sqf
  addons/main/functions/fnc_addPlate.sqf
  addons/main/functions/fnc_handleDamageEhACE.sqf
  addons/main/functions/fnc_receiveDamage.sqf
  addons/main/functions/fnc_receiveDamageACE.sqf
  addons/main/functions/fnc_showDamageFeedbackMarker.sqf
  addons/main/initSettings.sqf
  addons/main/initSettingsACE.sqf
  addons/main/script_component.hpp
  addons/main/stringtable.xml
Labels: enhancement

#13 Update stringtable.xml
  addons/main/stringtable.xml
Labels: translation

#15 fix friendly fire detection for zeus controlled units
  addons/main/functions/fnc_handleDamageEh.sqf
  addons/main/functions/fnc_handleDamageEhACE.sqf
  addons/main/functions/fnc_hitEh.sqf
Labels: bug

#20 Add more 3den properties
  addons/main/CfgEden.hpp
  addons/main/XEH_postInit.sqf
  addons/main/functions/fnc_initAIUnit.sqf
  addons/main/stringtable.xml
Labels: enhancement

#21 Change icon on downed unit if someone is helping them
  addons/main/XEH_postInit.sqf
  addons/main/functions/fnc_addActionsToUnit.sqf
  addons/main/functions/fnc_addPlayerHoldActions.sqf
  addons/main/functions/fnc_drawDownedUnitIndicator.sqf
  addons/main/functions/fnc_setUnconscious.sqf
Labels: enhancement

#23 Allow ai unconsciousness and request revive from ai
  addons/main/XEH_PREP.hpp
  addons/main/XEH_postInit.sqf
  addons/main/functions/fnc_aiMoveAndHealUnit.sqf
  addons/main/functions/fnc_receiveDamage.sqf
  addons/main/functions/fnc_requestAIRevive.sqf
  addons/main/functions/fnc_setUnconscious.sqf
  addons/main/initSettings.sqf
  tools/sqf_linter_LogChecker.py
Labels: enhancement

#24 Add zeus heal module
  addons/main/CfgFactionClasses.hpp
  addons/main/CfgVehicles.hpp
  addons/main/XEH_PREP.hpp
  addons/main/config.cpp
  addons/main/functions/fnc_moduleHeal.sqf
  addons/main/stringtable.xml
Labels: enhancement

#19 Add ace interaction to add plate
  addons/main/XEH_PREP.hpp
  addons/main/XEH_postInit.sqf
  addons/main/functions/fnc_addActionsToUnit.sqf
  addons/main/functions/fnc_addPlate.sqf
  addons/main/functions/fnc_addPlateKeyPress.sqf
  addons/main/stringtable.xml
Labels: enhancement

#25 Scale down plate hp in vest if setting has decreased (ACE mode)
  addons/main/initSettingsACE.sqf
Labels: bug

#27 Fix fall damage
  addons/main/functions/fnc_handleDamageEh.sqf
  addons/main/functions/fnc_hitEh.sqf
Labels: bug

#28 Fix damage indicators showing when standing near fire with ACE loaded
  .github/ISSUE_TEMPLATE/bug_report.md
  addons/main/functions/fnc_handleDamageEhACE.sqf
Labels: bug

#29 fix multiple ace interaction issues
  addons/main/XEH_postInit.sqf
Labels: bug

#26 Add filter damage for HandleDamage eh
  addons/main/functions/fnc_handleDamageEh.sqf
  addons/main/initSettings.sqf
  addons/main/stringtable.xml
Labels: enhancement
