Repository diwako/armor_plates_system, pull requests merged in 2021-08, with the labels that each got.

#38 Localisation Translation
  addons/main/stringtable.xml
Labels: translation

#50 disable third party medical if possible
  addons/main/CfgFunctions.hpp
  addons/main/XEH_PREP.hpp
  addons/main/XEH_preInit.sqf
  addons/main/config.cpp
  addons/main/functions/fnc_disableThirdParty.sqf
Labels: enhancement

#45 Add a visible bleedout timer over the downed icon
  addons/main/functions/fnc_drawDownedUnitIndicator.sqf
  addons/main/functions/fnc_setUnconscious.sqf
  addons/main/initSettings.sqf
  addons/main/stringtable.xml
Labels: enhancement

#46 Fix FAKs not being used on heal
  addons/main/XEH_postInit.sqf
  addons/main/functions/fnc_addActionsToUnit.sqf
  addons/main/functions/fnc_addPlayerHoldActions.sqf
  addons/main/functions/fnc_handleHealEh.sqf
  addons/main/functions/fnc_moduleHeal.sqf
  addons/main/functions/fnc_revive.sqf
Labels: bug

#47 More consistent animations
  addons/main/functions/fnc_addActionsToUnit.sqf
  addons/main/functions/fnc_addPlayerHoldActions.sqf
Labels: enhancement

#48 Fix adding plates on player respawn
  addons/main/XEH_PREP.hpp
  addons/main/XEH_postInit.sqf
  addons/main/functions/fnc_fillVestWithPlates.sqf
Labels: bug

#49 fix medic disconnect issue on reviving units
  addons/main/functions/fnc_addActionsToUnit.sqf
Labels: bug
